### ISSUE TITLE
Deprecated selector in `neon-syntax/index.less`

### ISSUE THREAD

**Issue by thegrimheep** [anomaly256/neon-syntax#11]
In `neon-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor.is-focused .cursor,
:host .cursor` => `atom-text-editor.is-focused .cursor,atom-text-editor .cursor`

* `atom-text-editor.is-focused .selection .region,
:host .selection .region` => `atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
:host .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,atom-text-editor .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line.cursor-line`

* `.comment` => `.syntax--comment`

* `.string` => `.syntax--string`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.character,
.constant.other` => `.syntax--constant.syntax--character,
.syntax--constant.syntax--other`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.storage` => `.syntax--storage`

* `.meta.function-call` => `.syntax--meta.syntax--function-call`

* `.support.function` => `.syntax--support.syntax--function`

* `.variable.other.external-symbol` => `.syntax--variable.syntax--other.external-symbol`

* `.variable.language,
.variable.other` => `.syntax--variable.syntax--language,
.syntax--variable.syntax--other`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.keyword` => `.syntax--keyword`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.name.class` => `.syntax--entity.syntax--name.syntax--class`

* `.entity.name.structure` => `.syntax--entity.syntax--name.syntax--structure`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.entity.name.function.io` => `.syntax--entity.syntax--name.syntax--function.syntax--io`

* `.entity.name.function.misc` => `.syntax--entity.syntax--name.syntax--function.syntax--misc`

* `.entity.name.function.predicate` => `.syntax--entity.syntax--name.syntax--function.syntax--predicate`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.meta.class,
.entity.name.class,
.entity.name.type.class` => `.syntax--meta.syntax--class,
.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.support.class` => `.syntax--support.syntax--class`

* `.invalid` => `.syntax--invalid`

* `.string .source` => `.syntax--string .syntax--source`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.markup.heading` => `.syntax--markup.syntax--heading`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.underline` => `.syntax--markup.syntax--underline`

* `.gfm .link .entity` => `.syntax--gfm .syntax--link .syntax--entity`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by anomaly256** [comment]
Thanks, will update soon

**Comment by anomaly256** [comment]
Closed by #12
