### ISSUE TITLE
Coloring gone after update to 0.3.7

### ISSUE THREAD

**Issue by jakobholmelund** [anomaly256/neon-syntax#14]
Just updated the neon package in Atom and all styling is gone :( 
![neongone](https://cloud.githubusercontent.com/assets/244930/22200880/6a79cdaa-e161-11e6-9c60-5844dd150374.png)

**Comment by anomaly256** [comment]
Hi, please check #13

**Comment by jakobholmelund** [comment]
Thanks :) maybe keep the other issue open for a bit ?

**Comment by anomaly256** [comment]
Done, changed the title to be more informative too.  closing this one then!
