### ISSUE TITLE
selection is not visible 

### ISSUE THREAD

**Issue by louisfm16** [anomaly256/neon-syntax#3]
default selection for Neon syntax wont show up, tried adding neon selection and is still not visible, also tried editing in application stylesheet and as like before it is still not visible.

**Comment by anomaly256** [comment]
Looks like this is due to the Shadow DOM change, works ok here with Shadow DOM disabled on Atom 0.165.0.  I'll investigate what I need to change to fix this, thanks

**Comment by anomaly256** [comment]
Hi @louisfm16, should work again now in v0.3.3 of the package
