### ISSUE TITLE
Needs more glow

### ISSUE THREAD

**Issue by aktowns** [anomaly256/neon-syntax#6]
like über glow

![http://i.imgur.com/HJlHnzn.png](http://i.imgur.com/HJlHnzn.png)

**Comment by anomaly256** [comment]
You've obviously missed the LESS vars in stylesheets/syntax-variables.less, Ashley :trollface:
```ruby
@opacity: 0.8;
@blur: 15px;
@contrast: 200%;
@saturation: 200%;
```

**Comment by v3ss0n** [comment]
This is GLORIUS!

**Comment by anomaly256** [comment]
GLOWrius?

**Comment by v3ss0n** [comment]
GLOWRIUS! Like Nuka-Cola-Quantum.

My mod:
![atom_ide2](https://cloud.githubusercontent.com/assets/419606/6999053/5a533ac8-dc1e-11e4-9a4e-c83e643bbaf0.png)

**Comment by anomaly256** [comment]
:sunglasses:

**Comment by anomaly256** [comment]
By the way v3ss0n, try this in your styles.less to colourize the file icons similarly to the syntax theme https://gist.github.com/anomaly256/36ebd8e36cdd7dec71f7
