### ISSUE TITLE
Single Line Bracket/Parenthesis Indicators Not Showing Up

### ISSUE THREAD

**Issue by reverendj1** [anomaly256/neon-syntax#8]
It seems that when an open and close bracket or parenthesis are on the same line, they are not being picked up and underlined correctly. It works fine when they are on separate lines though.
Works:
![image](https://cloud.githubusercontent.com/assets/9728953/14116753/570c2d88-f5af-11e5-977d-3952e65db08e.png)
Doesn't Work:
![image](https://cloud.githubusercontent.com/assets/9728953/14116746/4bdebb7e-f5af-11e5-94f9-1d865825c396.png)

**Comment by anomaly256** [comment]
It's been a while since I've done any maintenance on this theme, likely something changed in Atom in the time since which broke this.  I'll have a look tonight, thanks for pointing it out

**Comment by anomaly256** [comment]
Sorry I haven't had time to fix this yet, I haven't forgotten about it though

**Comment by reverendj1** [comment]
It looks like I put this:

`.editor, atom-text-editor::shadow {
  .bracket-matcher {
    position: absolute;
    border: 1px solid rgba(153, 0, 255, 0.4);
    background-color: rgba(153, 0, 255, 0.4);
  }
}`

in my styles.less to workaround the issue. I'm not sure if that will help or not.

**Comment by anomaly256** [comment]
Turns out the reason the bracket match indicator disappears on single line matches is due to z-index oddness introduced at some point...  I've fixed this now and will push an update shortly.  I've also taken the opportunity to theme the indicator a bit instead of relying on atom's default style for it.  Thanks

**Comment by anomaly256** [comment]
...as soon as I remember how to submit package updates :P

**Comment by reverendj1** [comment]
Looks like you remembered how to submit packages. I removed my workaround and it seems to be working great after pulling the new package. Thanks!

**Comment by anomaly256** [comment]
No worries, glad someone somewhere likes my theme!
