### ISSUE TITLE
adjusting blur

### ISSUE THREAD

**Issue by Benjamski** [anomaly256/neon-syntax#9]
I apologize if this is obvious, but how exactly do i access the css for the neon theme?

I only know how to get to the atom style sheet.

**Comment by anomaly256** [comment]
Usually it would be in ~/.atom/packages/neon-syntax/styles/base.less on unix-like systems.  If you're using Windows I'm not sure where the downloaded packages are stored

**Comment by Benjamski** [comment]
That's perfect, thanks!

**Comment by anomaly256** [comment]
No worries
